import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/Reusables/Header/Header'
import Footer from './components/Reusables/Footer'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Toaster  position='top-center' toastOptions={{style:{
        color:'white',
        backgroundColor:"red"
      }}}/>

        <Header/>
     <main >
     {children}
     </main>
     <Footer/>
      </body>
    </html>
  )
}
