import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Reusables/Header/Header";
import Footer from "./components/Reusables/Footer";
import { Toaster } from "react-hot-toast";
import { cookies } from "next/headers";
import { fetchUser } from "@/lib/fetch";
import { ServerActionResponse } from "@/types/app";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let session;
  const sessId = cookies().get("sessId")
  if(sessId)  {
     session = await fetchUser(sessId.value as string) as ServerActionResponse
  }


  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster
          position="top-center"
          toastOptions={{
            style: {
              color: "white",
              backgroundColor: "red",
            },
          }}
        />

        <Header session={session ? session as ServerActionResponse : null} />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
